"""Утилита для генерации схем из SQLAlchemy-моделей."""
from pathlib import Path
import typing as tp


def gen_scheme(input_: Path, output_: Path, module_prefix: str = 'cm', scheme_suffix: str = 'Schema(BaseSchema)',
               excluded_fields: tp.Iterable[str] = (), meta_suffix: str = '(BaseMeta)',
               marshmallow_fields_prefix: str = 'fields', description_default_param: str = 'DBStruct.default_description'):
    """
    Генерирует файл схемы на основе файла моделей SQLAlchemy. Предполагается, что для каждого Foreign Key имеется
    otm-отношение, расположенное в том же классе, что и FK и сделанное через relationship.

    Пример:
    Входной файл:

    <...>

    class SQLAlchemyModel(BaseModel):
        <...>
        creator_id: Mapped[int] = <...>
        creator: Mapped[CreatorModel] = relationship(<...>)
        description: Mapped[str] = <...>
        <...>

    <...>

    Выходной файл:

    <...>

    class SQLAlchemyModel<scheme_suffix>:
        class Meta<meta_suffix>:
            model = <module_prefix>SQLAlchemyModel

        creator_id = <marshmallow_fields_prefix>Int(load_only=True)
        creator = <marshmallow_fields_prefix>Int(dump_only=True)
        description = <marshmallow_fields_prefix>Str(load_default={description_default_param})

    <...>

    """
    if module_prefix:
        module_prefix = f'{module_prefix}.'
    if marshmallow_fields_prefix:
        marshmallow_fields_prefix = f'{marshmallow_fields_prefix}.'

    if output_.is_file():
        raise ValueError(f'Output-file already exists: {output_}.')

    with open(output_, 'w') as output_file:
        output_file.write('# Generated by scheme-model util (server.utils.scheme_generator)')

    with open(input_) as input_file:
        text = input_file.readlines(10000)
        model_now = None

        while text:
            result = []
            for line in text:
                if 'class' in line:  # Нашли класс модели
                    model_now = line.split()[1].split('(')[0]
                    result.append(f'\n\n'
                                  f'class {model_now}{scheme_suffix}:\n\n'
                                  f'    class Meta{meta_suffix}:\n'
                                  f'        model = {module_prefix}{model_now}\n'
                                  f'')

                if ':' in line:
                    field = line.split(':')[0].strip()
                    if '_id' in field and model_now:  # Нашли поле
                        entity = '_'.join(field.split('_')[0:-1]).strip()
                        if field not in excluded_fields:  # Записали поле внешнего ключа и relationship-поле
                            result.append(f'    {field} = {marshmallow_fields_prefix}Int(load_only=True)\n')
                            result.append(f'    {entity} = auto_field(dump_only=True)\n')
                    if field == 'description':
                        result.append(f'    {field} = {marshmallow_fields_prefix}Str(load_default={description_default_param})\n')

            with open(output_, 'a') as file:
                file.write(''.join(result))

            text = input_file.readlines(10000)


if __name__ == '__main__':
    gen_scheme('../database/models/common_models.py', Path('common.py'), module_prefix='cm')
